# Generated by Django 2.0.1 on 2018-02-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rank',
            new_name='weight',
        ),
    ]
